server:
  port: 9005
spring:
  application:
    name: tensquare-gathering #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.101.140.26:3306/tensquare_gathering?characterEncoding=UTF8&useSSL=false
    username: root
    password: admin
  jpa:
    database: MySQL
    show-sql: true
  redis:
    host: 47.101.140.26
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true